version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq_host
    restart: unless-stopped
    environment:
      TZ: "America/Mexico_City"
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - default

networks:
  default:
    external:
      name: local_network

volumes:
  rabbitmq_log:
  rabbitmq_data:









