version: '3.9'

services:
  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - default

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    links:
      - mongo
    restart: unless-stopped
    ports:
      - 8099:8081
    networks:
      - default

volumes:
  mongodb_data:
networks:
  default:
    external:
      name: local_network











