version: '3.9'

services:
  mongo:
    image: mongo:5.0
    container_name: mongo_db
    environment:
      - MONGO_INITDB_USERNAME=${DB_USER}
      - MONGO_INITDB_PASSWORD=${DB_PASSWORD}
      - TZ="America/Mexico_City"
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${DB_USER}:${DB_PASSWORD}@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - TZ="America/Mexico_City"
    links:
      - mongo
    restart: unless-stopped
    ports:
      - 8081

networks:
  default:
    external:
      name: local_network

volumes:
  mongodb_data:









