version: '3.7'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    environment: 
    - requirepass=$DB_PASSWORD
    - TZ="America/Mexico_City"
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - default  
   
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    restart: always
    environment:
      - REDIS_HOSTS=redis
      - HTTP_PASSWORD=$DB_PASSWORD
    ports:
      - 0:8081    
    networks:
      - default  

networks:
  default:
    external:
      name: local_network

volumes:
  redis_data:









